logging:
  file:
    name: greenrent_prod.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

level:
  '[org.springframework.web]': INFO
  '[org.hibernate]': INFO
  '[com.greenrent]': INFO



management:
  endpoint:
    web:
      exposure:
        include:['info','env','health','beans']

  info:
    env:
      enabled: true